# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnum', models.IntegerField(max_length=10)),
                ('cname', models.CharField(max_length=20)),
                ('c', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(max_length=5)),
                ('enrol_year', models.IntegerField(max_length=2)),
                ('enrol_semester', models.IntegerField(max_length=2)),
                ('cnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snum', models.IntegerField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('year', models.IntegerField(max_length=2)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='enrol',
            name='snum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Student'),
        ),
    ]
