# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cname',
            new_name='과목명',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cnum',
            new_name='과목번호',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='c',
            new_name='학점',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='이름',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sname',
            new_name='이메일',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='전화번호',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='학년',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='snum',
            new_name='학번',
        ),
        migrations.AddField(
            model_name='course',
            name='is_전공',
            field=models.BooleanField(default=True),
        ),
    ]
