# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_auto_20171106_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='과목명',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='과목번호',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='학점',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='enrol_semester',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='enrol_year',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='grade',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='이름',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='전화번호',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='학년',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='학번',
            field=models.IntegerField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
