# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0003_auto_20171106_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='학점',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='enrol_semester',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='enrol_year',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='학년',
        ),
        migrations.AlterField(
            model_name='course',
            name='과목번호',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='이메일',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='학번',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
