# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0004_auto_20171106_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrol',
            old_name='cnum',
            new_name='과목',
        ),
        migrations.RenameField(
            model_name='enrol',
            old_name='snum',
            new_name='학생',
        ),
    ]
