# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0005_auto_20171106_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='학점',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrol',
            name='수강학기',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrol',
            name='수강학년',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='학년',
            field=models.IntegerField(default=0),
        ),
    ]
