# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0006_auto_20171106_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrol',
            name='성적',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10, verbose_name='성적'),
        ),
    ]
