# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0007_enrol_성적'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrol',
            name='성적',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='성적'),
        ),
    ]
